# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import website_crawler_pb2 as website__crawler__pb2


class WebsiteCrawlerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrawlWebsite = channel.unary_unary(
                '/website_crawler.WebsiteCrawlerService/CrawlWebsite',
                request_serializer=website__crawler__pb2.WebsiteCrawlerRequest.SerializeToString,
                response_deserializer=website__crawler__pb2.WebsiteCrawlerResponse.FromString,
                )


class WebsiteCrawlerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CrawlWebsite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebsiteCrawlerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrawlWebsite': grpc.unary_unary_rpc_method_handler(
                    servicer.CrawlWebsite,
                    request_deserializer=website__crawler__pb2.WebsiteCrawlerRequest.FromString,
                    response_serializer=website__crawler__pb2.WebsiteCrawlerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'website_crawler.WebsiteCrawlerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WebsiteCrawlerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CrawlWebsite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/website_crawler.WebsiteCrawlerService/CrawlWebsite',
            website__crawler__pb2.WebsiteCrawlerRequest.SerializeToString,
            website__crawler__pb2.WebsiteCrawlerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
